# This is a basic workflow to help you get started with Actions

name: MasterCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events for the master branch and feature branches
on:
  push:
    branches: [ master, 'feature/**']
  pull_request:
    branches: [ master, 'feature/**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Test
      - name: Run unit test in debug build
        id: testDebug
        run: ./gradlew testDebugUnitTest

      # Assemble
      - name: Run assemble to debug
        run: ./gradlew assembleDebug

      - name: Run lint
        run: ./gradlew lint
